version: '3.9'
services:
  nodejs-app:
    image: nodejs:web
    container_name: node_application
    ports:
      - 80:80
 #   volumes:
  #    - nodejs-vol:/usr/share/nginx/html/

#volumes:
 # nodejs-vol:
  #  external: true 
    
